I'm going to need this syntax a little later: <img src="dataframe_anatomy.png"/>

# Object, method, function?


# Data Types
string
boolean
int
float

In [5]:
name = 'Imogen'
type(name)

str

In [6]:
name[2]

'o'

In [8]:
name[4] = y

NameError: name 'y' is not defined

In [12]:
name[0:4]+'y'+name[5]

'Imogyn'

In [13]:
x = 0.34
type(x)

float

In [15]:
i =1
type(i)

int

In [16]:
ans = True
type(ans)

bool

# structures
list
tuple
dict
set

## List

In [18]:
square = [1, 5, 9, 16, 25]
square

[1, 5, 9, 16, 25]

In [19]:
square[0]

1

In [20]:
square[1] =4

In [21]:
square

[1, 4, 9, 16, 25]

In [23]:
square + [36]

[1, 4, 9, 16, 25, 36]

In [24]:
square.append(49)

In [25]:
square

[1, 4, 9, 16, 25, 49]

In [26]:
x = [1,2,3]
y = [4,5]
A = [x,y]
A

[[1, 2, 3], [4, 5]]

In [28]:
A[1][1]

5

## Tuple

In [29]:
B = (1,2,3)

In [30]:
B[2]

3

In [31]:
B[2] =2

TypeError: 'tuple' object does not support item assignment

## Set

In [32]:
basket ={'chocolate','peaches','tomatoes','chocolate'}

In [33]:
basket

{'chocolate', 'peaches', 'tomatoes'}

In [34]:
basket[1]

TypeError: 'set' object is not subscriptable

## Dict

In [37]:
cars ={'prius':'toyota','bolt':'chevy','civic':'honda','accord':'honda'}

In [39]:
cars['accord']

'honda'

In [43]:
cars ={'prius':'toyota','camry':'toyota','bolt':'chevy','civic':'honda','accord':'honda','accord':'toyota'}

In [44]:
cars['camry']

'toyota'

In [42]:
cars

{'prius': 'toyota', 'bolt': 'chevy', 'civic': 'honda', 'accord': 'toyota'}

In [45]:
cars['toyota']

KeyError: 'toyota'

# Numpy

In [46]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a[0][2]

3

In [48]:
a[0,2]

3

In [51]:
a[0:3,1:]

array([[2, 3],
       [5, 6]])

In [60]:
a[0,::-1]

array([3, 2, 1])

# Pandas

In [87]:
L = np.array[1,'imogen',True]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [62]:
L

[1, 'imogen', True]

In [63]:
type(L[0])

int

In [64]:
import pandas as pd

In [69]:
fruit_info_dict ={'fruit':['apple','orange'],
                 'color':['red','orange'],
                 'weight':[100,200]}
fruit_info_dict['weight'][0]

100

In [70]:
fruit_info_df = pd.DataFrame(data = fruit_info_dict)

In [71]:
fruit_info_df

fruit   color  weight
0   apple     red     100
1  orange  orange     200

In [72]:
fruit_info_dict

{'fruit': ['apple', 'orange'],
 'color': ['red', 'orange'],
 'weight': [100, 200]}

In [73]:
fruit_info_df['color']

0       red
1    orange
Name: color, dtype: object

In [74]:
fruit_info_df.columns

Index(['fruit', 'color', 'weight'], dtype='object')

In [75]:
fruit_info_df.color

0       red
1    orange
Name: color, dtype: object

In [77]:
fruit_info_df['weight'][0:2]

0    100
1    200
Name: weight, dtype: int64

In [78]:
!ls

CAISO_2017to2018.csv                 Lecture 03.3 Numpy.pdf
Lecture 03 InClassNotebook.ipynb     Lecture 03.4 Pandas.ipynb
Lecture 03.1 DataTypes Pandas.pptx   Lecture 03.4 Pandas.pdf
Lecture 03.2 DataTypes.ipynb         dataframe_anatomy.png
Lecture 03.2 DataTypes.pdf           from drive
Lecture 03.3 Numpy.ipynb             ~$Lecture 03.1 DataTypes Pandas.pptx


In [80]:
caiso_df = pd.read_csv('CAISO_2017to2018.csv')

In [81]:
caiso_df

Unnamed: 0  GEOTHERMAL  BIOMASS  BIOGAS  SMALL HYDRO  \
0     2017-08-29 00:00:00        1181      340     156          324   
1     2017-08-29 01:00:00        1182      338     156          326   
2     2017-08-29 02:00:00        1183      337     156          337   
3     2017-08-29 03:00:00        1185      339     156          313   
4     2017-08-29 04:00:00        1190      344     156          320   
...                   ...         ...      ...     ...          ...   
8755  2018-08-28 19:00:00         962      332     236          581   
8756  2018-08-28 20:00:00         967      336     234          547   
8757  2018-08-28 21:00:00         972      336     233          502   
8758  2018-08-28 22:00:00         975      333     234          361   
8759  2018-08-28 23:00:00         977      333     235          262   

      WIND TOTAL  SOLAR PV  SOLAR THERMAL  
0           1551         0              0  
1           1556         0              0  
2           1325         0              0  
3           1158         0              0  
4           1209         0              0  
...          ...       ...            ...  
8755        3300        70             24  
8756        3468         0             17  
8757        3310         0             17  
8758        3068         0              0  
8759        2921         0              0  

[8760 rows x 8 columns]

<img src="dataframe_anatomy.png"/>

In [84]:
caiso_data = pd.read_csv('CAISO_2017to2018.csv', index_col=0)

In [85]:
caiso_data

GEOTHERMAL  BIOMASS  BIOGAS  SMALL HYDRO  WIND TOTAL  \
2017-08-29 00:00:00        1181      340     156          324        1551   
2017-08-29 01:00:00        1182      338     156          326        1556   
2017-08-29 02:00:00        1183      337     156          337        1325   
2017-08-29 03:00:00        1185      339     156          313        1158   
2017-08-29 04:00:00        1190      344     156          320        1209   
...                         ...      ...     ...          ...         ...   
2018-08-28 19:00:00         962      332     236          581        3300   
2018-08-28 20:00:00         967      336     234          547        3468   
2018-08-28 21:00:00         972      336     233          502        3310   
2018-08-28 22:00:00         975      333     234          361        3068   
2018-08-28 23:00:00         977      333     235          262        2921   

                     SOLAR PV  SOLAR THERMAL  
2017-08-29 00:00:00         0              0  
2017-08-29 01:00:00         0              0  
2017-08-29 02:00:00         0              0  
2017-08-29 03:00:00         0              0  
2017-08-29 04:00:00         0              0  
...                       ...            ...  
2018-08-28 19:00:00        70             24  
2018-08-28 20:00:00         0             17  
2018-08-28 21:00:00         0             17  
2018-08-28 22:00:00         0              0  
2018-08-28 23:00:00         0              0  

[8760 rows x 7 columns]

In [86]:
caiso_data['SMALL HYDRO']['2018-08-28 22:00:00']

361